### ISSUE TITLE
Atlante_carto_pa

### ISSUE THREAD

**Issue by aborruso** [gbvitrano/Maps#3]
Correggere ordine autori in informazioni: è un lavoro realizzato per la gran parte da @gbvitrano , quindi per favore mettilo per primo!!

**Comment by gbvitrano** [comment]
Sono messi in ordine al alfabetico :-) 
il progetto non sarebbe esistito senza il contributo di tutti,  mi sono limitato ad assemblare tutto il materiale

**Comment by aborruso** [comment]
@gbvitrano lo vedo, però il tuo tempo è stato tanto. Io ci terrei a vederti per primo, è giusto, te lo meriti.
Ma l'autore sei tu, quindi a te la scelta ;)

**Comment by gbvitrano** [comment]
@aborruso ti ringrazio, ma va bene cosi :-)  per essere in ordine alfabetico giusto devo spostare Ciro :-)
